# Generated by Django 4.2.14 on 2024-07-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='financial_situation',
            field=models.CharField(blank=True, choices=[('N', 'Need-based aid'), ('M', 'Merit-based aid')], max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('O', 'Other'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade'), ('F', 'College Freshman'), ('S', 'College Sophomore'), ('J', 'College Junior'), ('S', 'College Senior')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
