# Generated by Django 4.2.14 on 2024-08-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_financial_situation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mentor_or_mentee',
        ),
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='financial_situation',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('N', 'Need-based aid'), ('M', 'Merit-based aid')], max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade'), ('F', 'College Freshman'), ('S', 'College Sophomore'), ('J', 'College Junior'), ('S', 'College Senior')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
